### PR TITLE
Added my name to the contributors list

### PR DESCRIPTION
**Pull request by Fatima-Bint**

### CODE REVIEW

**Comment by codewithmide** [comment]
LGTM well done @Fatima-Bint

**Comment by Fatima-Bint** [comment]
Thank you

**Comment by Fatima-Bint** [comment]
> LGTM well done @Fatima-Bint

What does LGTM mean though? @codewithmide

**Comment by codewithmide** [comment]
Look good to me

**Comment by Fatima-Bint** [comment]
> Look good to me

I see. I never knew. Thanks

**Pull request closed without merging**
