### PR TITLE
updated README

### PR DESCRIPTION
**Pull request by uju-juelle**
I have created my folder and README.md file. I have also done the introductions and added the checklists for contributions. I also added my name according in the list of Contributors

### CODE REVIEW

**Comment by codewithmide** [comment]
Hi @uju-juelle, it seems your readme is empty. Kindly cross check it

**Comment by thibaudcolas** [comment]
Indeed the file is empty @uju-juelle :) I’ll add it anyway but you’ll need to add the contents later.

**Comment by uju-juelle** [comment]
Thank you mide.

**Comment by uju-juelle** [comment]
Thank you Sir Thibaud i will update it. I added it but don't know why it is empty. will add the contents again

**Pull request merged**
