### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Afola-Ode**

### CODE REVIEW

**Comment by Afola-Ode** [comment]
updated readme for 2023 participants

**Comment by codewithmide** [comment]
Hi @Afola-Ode, well done for making your first contribution. Please do not forget that there are other tasks awaiting in the [contribution guide](https://github.com/wagtail/outreachy/blob/main/contributor-guide.md)

**Comment by Chinex-Boroja** [comment]
> _ No description provided. _

@Afola-Ode Just in case, you can list or simply describe the tasks you carried out in the description section. So that the reviewer can at least know what you have done

**Comment by thibaudcolas** [comment]
@codewithmide @Chinex-Boroja if this is someone’s first contribution adding their name there’s not much to be said :) I think just a name is fine.

Welcome to the club @Afola-Ode!

**Pull request merged**
