### PR TITLE
Added README.md contents and updated my name in the List

### PR DESCRIPTION
**Pull request by uju-juelle**
I added my name to the list of contributors

### CODE REVIEW

**Comment by codewithmide** [comment]
Hi @uju-juelle, it seems there is a conflict in your PR, kindly review it once more.

**Comment by uju-juelle** [comment]
I have tried resolving the conflicts with the branch as the conflict was from the README.md where i updated my name in the list of contributors.

**Comment by uju-juelle** [comment]
> Hi @uju-juelle, it seems there is a conflict in your PR, kindly review it once more.

thank you @olumide. i have tried to do it but you can still check it out to give suggestions on how best to resolve it. added the conflict resolution in this pull request.

**Comment by thibaudcolas** [comment]
@uju-juelle this needs further work. Conflicts in `2023/README.md` should be very simple to resolve. Conflicts in your own file will only come from how you edit your own content, so I think it’s important you learn to resolve this on your own.

Please go through more fundamental GitHub / git knowledge training before having another go at this.

**Pull request closed without merging**
