### PR TITLE
Updated my blog posts 

### PR DESCRIPTION
**Pull request by ginandze**
Updated my blog posts to meet grade 7 standard on Hemingway Editor and also formatted the readme file to look better.
I ticked off some tasks off my checklist as well.

### CODE REVIEW

**Comment by codewithmide** [comment]
Hi @ginandze, I noticed there's a conflict in your branch. Kindly make sure to pull before pushing again

**Comment by ginandze** [comment]
> Hi @ginandze, I noticed there's a conflict in your branch. Kindly make sure to pull before pushing again

Thank you @codewithmide, I keep learning from you :).
I think I resolved the conflicts. I hope its ok now?

**Comment by codewithmide** [comment]
> > Hi @ginandze, I noticed there's a conflict in your branch. Kindly make sure to pull before pushing again
> 
> Thank you @codewithmide, I keep learning from you :). I think I resolved the conflicts. I hope its ok now?

Yeah, it is better now. Good Job!

**Comment by ginandze** [comment]
> > Hi @ginandze, I noticed there's a conflict in your branch. Kindly make sure to pull before pushing again
> 
> Thank you @codewithmide, I keep learning from you :). I think I resolved the conflicts. I hope its ok now?



> > > Hi @ginandze, I noticed there's a conflict in your branch. Kindly make sure to pull before pushing again
> > 
> > 
> > Thank you @codewithmide, I keep learning from you :). I think I resolved the conflicts. I hope its ok now?
> 
> Yeah, it is better now. Good Job!

:)

**Review by thibaudcolas — APPROVED** [review]

**Pull request merged**
