### PR TITLE
Reach me updated checklist

### PR DESCRIPTION
**Pull request by Amalearner**

### CODE REVIEW

**Comment by Amalearner** [comment]
Hello @thibaudcolas i don't know how to resolve this conflict. i was supposed to create a new branch

**Comment by Amalearner** [comment]
Yeah. I do 😔. Don't know what to do

**Comment by Amalearner** [comment]
I closed the pull request and deleted the branch. After I saw where the conflict was coming from.

**Comment by geoffreylgv** [comment]
> I closed the pull request and deleted the branch. After I saw where the conflict was coming from. @geoffreylgv

- First update your forked repository `main` branch, 
- and then, clone repository to your laptop
VS Code can help you resolve these conflicts locally, then push; If you need a help, let me know

**Comment by Amalearner** [comment]
@geoffreylgv in your DM on slack

**Comment by codewithmide** [comment]
@Amalearner Has it been resolved? If not, you might need to reclone the repository and add your changes. You don't need to create another branch, just push to the main branch and submit a new PR.

**Comment by Amalearner** [comment]
@codewithmide thanks. @geoffreylgv has helped guide me 🙏

**Pull request closed without merging**
