### PR TITLE
Reach me

### PR DESCRIPTION
**Pull request by Amalearner**

### CODE REVIEW

**Comment by codewithmide** [comment]
Hi @Amalearner, Please remember to add your introductory message and socials as well

**Comment by Amalearner** [comment]
I did. It's showing on my end. Can you send a screenshot of what it's showing on your end? @codewithmide

**Comment by codewithmide** [comment]
Oh yes, it is showing. Well done 👏

**Comment by Amalearner** [comment]
Thank you 🥹🥹🥹 @codewithmide

**Comment by Ozyugoo** [comment]
> _ No description provided. _

Hi @Amalearner,

Remember to add a description to your pull request.

**Comment by Amalearner** [comment]
> Looking good!

Thank you @thibaudcolas

**Pull request merged**
