### PR TITLE
doc: how-to-contribute guide

### PR DESCRIPTION
**Pull request by ArafatAbdussalam**
Hi @thibaudcolas,

From the conversations on the Slack workspace, new contributors find it challenging to make their contribution an easy experience. Hence, I decided to write a how-to-contribute-guide markdown file to help current and upcoming Outreachy participants.

### CODE REVIEW

**Comment by codewithmide** [comment]
Well done for taking this initiative @ArafatAbdussalam 

Do you mind including the steps they need to take when creating thier own personal directory and the required information they need to add in thier readme file.

**Comment by ArafatAbdussalam** [comment]
Hi @codewithmide the steps are also included. Adding names to the READme file basically requires editing of the respective file, following git add, git commit and git push

**Comment by Ozyugoo** [comment]
> Hi @thibaudcolas,
> 
> From the conversations on the Slack workspace, new contributors find it challenging to make their contribution an easy experience. Hence, I decided to write a how-to-contribute-guide markdown file to help current and upcoming Outreachy participants.

Well done @ArafatAbdussalam, that was very thoughtful of you.

**Comment by Fatima-Bint** [comment]
This is good. Thank you. I would like to add a few details when it's merged.

**Comment by thibaudcolas** [comment]
@ArafatAbdussalam I appreciate the initiative here :) I don’t think we want this though, for two reasons: this is meant to be challenging, and methodologically as far as working with this repository I think it’d be much simpler for people to do this all in GitHub’s interface. There are only two files to change after all.

If you want to take this forward I’d suggest you nonetheless share your guide with people you’re helping. A Gist: https://gist.github.com/ would be a great format for this, so people can provide feedback / star / share it easily.

If there are specific aspects of the existing guide you think could be improved, please do follow up.

---

On the methodological side,

- Knowledge of the command line as shown in those instructions is yet another hurdle that people don’t need to go through
- I’d much rather see people do this in GitHub so they don’t have to figure out how to install git locally (unless they really want to). We shouldn’t suggest doing this locally with git is the best or only option.
- Your steps will fail at `git push`, because people who do this will also need it to either use a personal access token or SSH auth

On the philosophical side, literally knowledge of git and GitHub is mentioned as one of our fundamental expectations for people taking part:

> No matter which specific project idea you’re interested in, we expect all participants to demonstrate:
> 
> […]
> - Knowledge of **git and GitHub**: coders or not, those are fundamental tools for how we work as a community.

And as part of the "open source contributions" checklist, two of those links offer a good mixture of good high-level and detailed information about making pull requests:

> - [ ] Read through [How to contribute to open source](https://opensource.guide/how-to-contribute/)
> - [ ] Read [Open source etiquette](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette)
> - [ ] Make your first [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) with us! Add your name to the list of participants in [2023/README.md](2023/README.md).

**Comment by ArafatAbdussalam** [comment]
Okay @thibaudcolas Thank you for the feedback. I appreciate it a lot.

**Pull request closed without merging**
